In [1]:
import numpy as np

# Question 3

### b

In [2]:
# Influence matrix according to the question 
T = np.array([[0, 0, 1, 0], [3/5, 0, 0, 2/5], [0, 1, 0, 0], [0, 0, 1, 0]])

# initial opinions
p0 = np.array([1, 0, 1, 1])

# Matrix does not converge
prev_p = p0
p = T.dot(prev_p)
step = 0
while not np.allclose(p, prev_p):
    step += 1
    prev_p = p
    p = T.dot(prev_p)
    print("Step #", step)
    print(p)
    print
    if step > 1000:
        break

Step # 1
[0. 1. 1. 0.]
Step # 2
[1. 0. 1. 1.]
Step # 3
[1. 1. 0. 1.]
Step # 4
[0. 1. 1. 0.]
Step # 5
[1. 0. 1. 1.]
Step # 6
[1. 1. 0. 1.]
Step # 7
[0. 1. 1. 0.]
Step # 8
[1. 0. 1. 1.]
Step # 9
[1. 1. 0. 1.]
Step # 10
[0. 1. 1. 0.]
Step # 11
[1. 0. 1. 1.]
Step # 12
[1. 1. 0. 1.]
Step # 13
[0. 1. 1. 0.]
Step # 14
[1. 0. 1. 1.]
Step # 15
[1. 1. 0. 1.]
Step # 16
[0. 1. 1. 0.]
Step # 17
[1. 0. 1. 1.]
Step # 18
[1. 1. 0. 1.]
Step # 19
[0. 1. 1. 0.]
Step # 20
[1. 0. 1. 1.]
Step # 21
[1. 1. 0. 1.]
Step # 22
[0. 1. 1. 0.]
Step # 23
[1. 0. 1. 1.]
Step # 24
[1. 1. 0. 1.]
Step # 25
[0. 1. 1. 0.]
Step # 26
[1. 0. 1. 1.]
Step # 27
[1. 1. 0. 1.]
Step # 28
[0. 1. 1. 0.]
Step # 29
[1. 0. 1. 1.]
Step # 30
[1. 1. 0. 1.]
Step # 31
[0. 1. 1. 0.]
Step # 32
[1. 0. 1. 1.]
Step # 33
[1. 1. 0. 1.]
Step # 34
[0. 1. 1. 0.]
Step # 35
[1. 0. 1. 1.]
Step # 36
[1. 1. 0. 1.]
Step # 37
[0. 1. 1. 0.]
Step # 38
[1. 0. 1. 1.]
Step # 39
[1. 1. 0. 1.]
Step # 40
[0. 1. 1. 0.]
Step # 41
[1. 0. 1. 1.]
Step # 42
[1. 1. 0. 1.]
S